# Generated by Django 5.0.6 on 2024-06-07 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsearch',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
